### ISSUE TITLE
The main network crashes with the error

### ISSUE THREAD

**Issue by fenix120486** [dreams-money/merged-mining-pool#4]
The test network is working.

The main network crashes with the error:
2023/11/03 11:31:23 New Stratum Connection from: 192.168.2.108
2023/11/03 11:31:23 New subscription from client type: GodMiner/1.0.0
panic: runtime error: index out of range [1] with length 1

goroutine 38 [running]:
designs.capital/dogepool/pool.miningAuthorize(0xc000196ec0, 0xc000148fc0, 0xc00013ea20)
	/home/fenix73rus/My/merged-mining-pool-master-new/pool/responses.go:133 +0xd45
designs.capital/dogepool/pool.handleStratumRequest(0xc0000102e8?, 0x50fbb6e26?, 0x9ab7e0?)
	/home/fenix73rus/My/merged-mining-pool-master-new/pool/responses.go:51 +0x1da
designs.capital/dogepool/pool.(*PoolServer).respondToStratumClient(0xc00013ea20, 0xc000148fc0, {0xc0002bec00, 0x38, 0x400})
	/home/fenix73rus/My/merged-mining-pool-master-new/pool/responses.go:38 +0xc5
designs.capital/dogepool/pool.(*PoolServer).handleStratumConnection(0xc00013ea20, 0xc000148fc0)
	/home/fenix73rus/My/merged-mining-pool-master-new/pool/network.go:122 +0x2ed
designs.capital/dogepool/pool.(*PoolServer).openNewConnection(0xc0002b80d0?, 0xc000148fc0, 0x0?)
	/home/fenix73rus/My/merged-mining-pool-master-new/pool/network.go:88 +0x27
created by designs.capital/dogepool/pool.(*PoolServer).listenForConnections
	/home/fenix73rus/My/merged-mining-pool-master-new/pool/network.go:76 +0x398
exit status 2

**Comment by fenix120486** [comment]
https://github.com/dreams-money/merged-mining-pool/blob/969f3b916b8126744665995c7bb40052531d41db/bitcoin/litecoin.go#L26

I think the error comes from this line. In the previous version I changed the value to 43. This helped me. But this doesn't work in the new version.

**Comment by dreams-money** [comment]
Corrected by a3732d493b1082d5963f0c7bca5270e110999a41
