### ISSUE TITLE
The pool cannot pay out the coin to the owner.

### ISSUE THREAD

**Issue by fenix120486** [dreams-money/merged-mining-pool#5]
An error occurs when paying out a coin.

`2024/02/21 11:37:22 Awarding 6.1875 litecoin SOLO reward to miner tltc1q7yk4ujy6kazqhh2jzw9c0eewm732ghnulc3m7u-naKUcrqLXL74dAjKRUD1cTtp5gA9s5A4sL for work on litecoin block 3168261
2024/02/21 11:37:22 Awarding 6.1875 litecoin SOLO reward to miner tltc1q7yk4ujy6kazqhh2jzw9c0eewm732ghnulc3m7u-naKUcrqLXL74dAjKRUD1cTtp5gA9s5A4sL for work on litecoin block 3168265
2024/02/21 11:37:22 Valid share for block 3168367 from 172.16.5.1 [fenix]
panic: assignment to entry in nil map

goroutine 23 [running]:
designs.capital/dogepool/payouts.bitcoinTryManyPayments({0xc0007600e0, 0x1, 0x17?}, 0xc0000fc280, 0x8?)
  /home/fenix/mining/merged-mining-pool-master/payouts/payer.go:34 +0x12b
designs.capital/dogepool/payouts.payoutBalances(0xc0000fc280, 0xc00050de48?)
  /home/fenix/mining/merged-mining-pool-master/payouts/payer.go:27 +0x2ce
designs.capital/dogepool/payouts.RunManager(0xc0000fc280, 0x0?, 0x0?)
  /home/fenix/mining/merged-mining-pool-master/payouts/manager.go:55 +0x6d1
created by main.startPayoutService in goroutine 1
  /home/fenix/mining/merged-mining-pool-master/main.go:64 +0x9a
exit status 2`

If you fix the code in this line.
https://github.com/dreams-money/merged-mining-pool/blob/25cd2f8b3754802bf6002487d34484b254c0f7cc/payouts/payer.go#L31

Let's fix it like this.

`func bitcoinTryManyPayments(balances []persistence.Balance, config *config.Config, rpcManagers map[string]*rpc.Manager) error {
 transactionsGroupedByChain := make(map[string]map[string]float32)
 for _, balance := range balances {
  if transactionsGroupedByChain[balance.Chain] == nil {
   transactionsGroupedByChain[balance.Chain] = make(map[string]float32)
  }
  transactionsGroupedByChain[balance.Chain][balance.Address] = balance.Amount
 }`

A new error occurs: invalid wallet address Dogecoin.

`2024/02/22 14:28:28 HTTP 500: Invalid Dogecoin address: tltc1qjrew2rt9ukv27xv9cw7zlddht3dqqm49tvetmm-ngTpVqeCoPizCNn741cT887TfbMh1CC4of
2024/02/22 14:28:38 HTTP 500: Dummy value must be set to ""
`

**Comment by dreams-money** [comment]
Thank you so much for testing this.   The issue has been corrected with 5fd1852f4256c893163129348064ba702ae21b8f and 9eb3edef6cf8db57cce2f55213000e0b31f94af9 respectively.

**Comment by dreams-money** [comment]
Thank you so much for testing this. The issue has been corrected with https://github.com/dreams-money/merged-mining-pool/commit/5fd1852f4256c893163129348064ba702ae21b8f and https://github.com/dreams-money/merged-mining-pool/commit/9eb3edef6cf8db57cce2f55213000e0b31f94af9 respectively.

**Comment by dreams-money** [comment]
Thank you so much for testing this. The issue has been corrected with https://github.com/dreams-money/merged-mining-pool/commit/5fd1852f4256c893163129348064ba702ae21b8f and https://github.com/dreams-money/merged-mining-pool/commit/9eb3edef6cf8db57cce2f55213000e0b31f94af9 respectively.
