### ISSUE TITLE
Frontend

### ISSUE THREAD

**Issue by wombatlabs** [dreams-money/merged-mining-pool#7]
Hi is there a frontend that can be used with this pool?

**Comment by dreams-money** [comment]
No. It’s best to keep those two concerns separate.  The API is available for any custom website. Sent from my iPhoneOn May 3, 2024, at 10:15 PM, wombatlabs ***@***.***> wrote:﻿
Hi is there a frontend that can be used with this pool?

**Comment by wombatlabs** [comment]
Do you know of one that would be a good starting point?

**Comment by dreams-money** [comment]
I don’t unfortunately. Sent from my iPhoneOn May 4, 2024, at 7:00 PM, wombatlabs ***@***.***> wrote:﻿
Do you know of one that would be a good starting point?

**Comment by dreams-money** [comment]
A front end should be developed independently from the pool.
